ame: Feature Branch CI

on:
  push:
    branches: 
      - '**'
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
    - name: List directory contents
    - run: mvn test --file ./tictactoe-project/pom.xml
